import dayjs from 'dayjs';

function getTime(day = 0, second = 0) {
  return dayjs()
    .add(day, 'days')
    .add(second, 'seconds')
    .format('YYYY.MM.DD HH:mm:ss');
}

export const initData = async (clientId, nextSeq) => {
  return {
    // 회원
    user: [
      {
        _id: await nextSeq('user'),
        email: 'admin@market.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '무지',
        phone: '01011112222',
        address: '서울시 강남구 역삼동 123',
        type: 'admin',
        loginType: 'email',
        image: `files/${clientId}/user-muzi.png`,
        createdAt: getTime(-100, -60 * 60 * 3),
        updatedAt: getTime(-100, -60 * 60 * 3),
        extra: {
          birthday: '03-23',
        },
      },
      {
        _id: await nextSeq('user'),
        email: 's1@market.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '네오',
        phone: '01022223333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        loginType: 'email',
        image: `files/${clientId}/user-neo.png`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
        extra: {
          birthday: '11-23',
        },
      },
      {
        _id: await nextSeq('user'),
        email: 's1@market.com',
        password:
          '$2b$10$S.8GNMDyvUF0xzujPtHBu.j5gtS19.OhRmYbpJBnCHg2S83WLx1T2',
        name: '테스트',
        phone: '01022223333',
        address: '서울시 강남구 삼성동 456',
        type: 'seller',
        loginType: 'email',
        image: `files/${clientId}/user-neo.png`,
        createdAt: getTime(-50),
        updatedAt: getTime(-30, -60 * 60 * 3),
        extra: {
          birthday: '11-23',
        },
      },
    ],

    // 상품
    product: [
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근1',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이1',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯1',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근2',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이2',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯2',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근3',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이3',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯3',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근4',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이4',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯4',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근5',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근5',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근5',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근5',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근5',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근5',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 1990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '바니바니바니바니 당근당근5',
        quantity: 320,
        buyQuantity: 310,
        mainImages: [
          {
            path: `/files/${clientId}/product-1.jpeg`,
            name: 'product-1.jpeg',
            originalname: 'product-1.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-41, -60 * 60 * 2),
        updatedAt: getTime(-40, -60 * 15),
        extra: {
          isBest: true,
          category: ['당근', '채소'],
          details: '150g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 2,
        price: 2990,
        shippingFees: 0,
        show: true,
        active: true,
        name: '고구마 답답이5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-2.jpeg`,
            name: 'product-2.jpeg',
            originalname: 'product-2.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: true,
          category: ['고구마', '과일'],
          details: '500g',
        },
      },
      {
        _id: await nextSeq('product'),
        seller_id: 1,
        price: 2150,
        shippingFees: 0,
        show: true,
        active: true,
        name: '브라운 양송이버섯5',
        quantity: 200,
        buyQuantity: 198,
        mainImages: [
          {
            path: `/files/${clientId}/product-3.jpeg`,
            name: 'product-3.jpeg',
            originalname: 'product-3.jpeg',
          },
        ],
        content: ``,
        createdAt: getTime(-38, -60 * 60 * 6),
        updatedAt: getTime(-33, -60 * 55),
        extra: {
          isBest: false,
          category: ['양송이버섯', '채소'],
          details: '150g',
        },
      },
    ],

    // 주문
    order: [
      {
        _id: await nextSeq('order'),
        user_id: 1,
        state: 'OS020',
        products: [
          {
            _id: 1,
            seller_id: 2,
            state: 'OS020',
            name: '바니바니바니바니 당근당근1',
            image: {
              path: `/files/${clientId}/product-1.jpeg`,
              name: 'product-1.jpeg',
              originalname: 'product-1.jpeg',
            },
            quantity: 2,
            price: 1990,
            review_id: 3,
            extra: {
              isBest: true,
              category: ['당근', '채소'],
              details: '150g',
            },
          },
        ],
        cost: {
          products: 3980,
          shippingFees: 0,
          discount: {
            products: 0,
            shippingFees: 0,
          },
          total: 3980,
        },
        address: {
          name: '회사',
          value: '서울시 강남구 신사동 234',
        },
        createdAt: getTime(-6, -60 * 60 * 3),
        updatedAt: getTime(-6, -60 * 60 * 3),
      },
      {
        _id: await nextSeq('order'),
        user_id: 1,
        state: 'OS010',
        products: [
          {
            _id: 2,
            seller_id: 2,
            state: 'OS010',
            name: '고구마 답답이1',
            image: {
              path: `/files/${clientId}/product-2.jpeg`,
              name: 'product-2.jpeg',
              originalname: 'product-2.jpeg',
            },
            quantity: 1,
            price: 2990,
            extra: {
              isBest: true,
              category: ['고구마', '과일'],
              details: '500g',
            },
          },
          {
            _id: 3,
            seller_id: 1,
            state: 'OS010',
            name: '브라운 양송이버섯1',
            image: {
              path: `/files/${clientId}/product-3.jpeg`,
              name: 'product-3.jpeg',
              originalname: 'product-3.jpeg',
            },
            quantity: 2,
            price: 2150,
            review_id: 2,
            extra: {
              isBest: false,
              category: ['양송이버섯', '채소'],
              details: '150g',
            },
          },
        ],
        cost: {
          products: 7290,
          shippingFees: 0,
          discount: {
            products: 0,
            shippingFees: 0,
          },
          total: 7290,
        },
        address: {
          name: '집',
          value: '서울시 강남구 역삼동 123',
        },
        createdAt: getTime(-4, -60 * 60 * 22),
        updatedAt: getTime(-2, -60 * 60 * 12),
      },
    ],

    // 후기
    review: [],

    // 장바구니
    cart: [
      {
        _id: await nextSeq('cart'),
        user_id: 1,
        product_id: 1,
        quantity: 2,
        createdAt: getTime(-7, -60 * 30),
        updatedAt: getTime(-7, -60 * 30),
      },
    ],

    // 즐겨찾기/북마크
    bookmark: [
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        user: {
          _id: 4,
          name: '제이지',
          image: `files/${clientId}/user-jayg.webp`,
        },
        type: 'product',
        target_id: 1,
        memo: '첫째 크리스마스 선물.',
        createdAt: getTime(-3, -60 * 60 * 2),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        user: {
          _id: 4,
          name: '제이지',
          image: `files/${clientId}/user-jayg.webp`,
        },
        type: 'product',
        target_id: 2,
        memo: '둘째 생일 선물',
        createdAt: getTime(-1, -60 * 60 * 12),
      },
      {
        _id: await nextSeq('bookmark'),
        user_id: 1,
        user: {
          _id: 4,
          name: '제이지',
          image: `files/${clientId}/user-jayg.webp`,
        },
        type: 'post',
        target_id: 1,
        memo: '크기 문의글 북마크',
        createdAt: getTime(-1, -60 * 60 * 12),
      },
    ],

    // 코드
    code: [],

    // 설정
    config: [],
  };
};
